SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetMaterials]
    @MaterialIds NVARCHAR(MAX)
AS
BEGIN
SELECT *
FROM Material
WHERE Id IN (SELECT value FROM STRING_SPLIT(@MaterialIds, ','))
END;
GO
